micronaut:
  application:
    name: color-composer
  http:
    client:
      ws:
        compression:
          enabled: false # Default is true, results in NoClassDefFoundError: com/jcraft/jzlib/Deflater
datasources:
  default:
    driver-class-name: org.h2.Driver
    dialect: H2
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password: ""

# For hbm2ddl.auto property the list of possible options is:
# validate: validate that the schema matches, make no changes to the schema of the database, you probably want this for production.
# update: update the schema to reflect the entities being persisted
# create: creates the schema necessary for your entities, destroying any previous data.
# create-drop: create the schema as in create above, but also drop the schema at the end of the session. This is great in early development or for testing.
jpa:
  default:
    entity-scan:
      packages: 'io.cyborgsquirrel.entity'
    properties:
      hibernate:
        hbm2ddl:
          auto: create

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration/h2