micronaut:
  application:
    name: color-composer
  http:
    client:
      ws:
        compression:
          enabled: false # Default is true, results in NoClassDefFoundError: com/jcraft/jzlib/Deflater
  server:
    cors:
      enabled: true

datasources:
  default:
    driver-class-name: org.h2.Driver
    dialect: H2
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password: ""

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration/h2