micronaut:
  application:
    name: color-composer
  http:
    client:
      ws:
        compression:
          enabled: false # Default is true, results in NoClassDefFoundError: com/jcraft/jzlib/Deflater
  server:
    cors:
      enabled: true

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/colorcomposer`}
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    username: postgres
    password: test123

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration/postgres